server:
   port: 8000
my:
  uuid: ${random.uuid}

#default dateSource: org.apache.tomcat.jdbc.pool.DataSource
spring: 
   datasource: 
      #配置默认数据源的类型，就可以将数据库连接池变成druid  可通过DemoTest的测试方法查看
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/boot
      username: root
      password: 123456
# AOP
#   aop: 
#        auto: true
#        proxy-target-class: true
   #Spring MVC view prefix/suffix 
   mvc: 
     view: 
        prefix: /WEB-INF/jsp/
        suffix: .jsp
#   springboot 默认配置的 /** 映射到 /static （或/public、/resources、/META-INF/resources）
#   /static/**会映射到classpath:/static/
        static-path-pattern: /static/**
       
##默认以下配置生效,无此配置则通过启动类中MapperScan扫描xml
mybatis:
   typeAliasesPackage: cn.edu.ntu.entity
   mapper-locations: classpath:mappers/*.xml
   # 加载全局的配置文件
   configLocation: classpath:mybatis-config.xml

#log
logging: 
   level: 
      org: 
        apache.ibatis: debug
        springframework.web: debug
      cn.edu.ntu: debug