server:
   port: 8000
   #context-path: /wpfc
   tomcat.uri-encoding: UTF-8
   
my:
  uuid: ${random.uuid}

#default dateSource: org.apache.tomcat.jdbc.pool.DataSource
spring: 
   datasource: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/boot
      username: root
      password: 123456
   http: 
      encoding: 
          force: true
          charset: UTF-8
          enabled: true
      
#log
logging: 
   level: 
      org: 
        apache.ibatis: debug
        springframework.web: debug
      cn.edu.ntu: debug
   charset: utf-8